---
include:
  - remote: 'https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.17/workflow-default.yml'
  - remote: 'https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.17/terraform-toolkit.yml'
  - remote: 'https://raw.githubusercontent.com/miquido/gitlab-templates/1.3.17/git-toolkit.yml'

get-latest-terraform:
  extends: .get-latest-terraform

check-formatting:
  extends: .check-formatting

validate:
  extends: .validate
  variables:
    ENVIRONMENTS: examples/complete

bump-tag:
  extends: .bump_minor_tag
